import health from '../../../public/assets/article/health.svg';
import map from '../../../public/assets/article/karta.svg';
import openCity from '../../../public/assets/article/open-city.svg';
import uslugi from '../../../public/assets/article/uslugi.svg';

export const services = [
  {
    id: 1,
    title: 'Здоровье петербуржца',
    subtitle: 'Краткое описание Поддержка и развитие регионов  и развитие регионов',
    image: health,
    type: 'top',
    tag: 'discussed',
    rating: 4.3,
  },
  {
    id: 2,
    title: 'Твой бюждет',
    subtitle: 'Краткое описание Поддержка и развитие регионов  и развитие регионов',
    mark: 'popular',
    image: openCity,
    type: 'top',
    tag: 'discussed',
    rating: 4.5,
  },
  {
    id: 3,
    title: 'Наш Санкт-Петербург',
    subtitle: 'Краткое описание Поддержка и развитие регионов  и развитие регионов',
    mark: 'popular',
    image: uslugi,
    type: 'bottom',
    tag: 'popular',
    rating: 3.5,
  },
  {
    id: 4,
    title: 'Мои документы',
    subtitle: 'Государственные и муниципальные услуги',
    mark: 'popular',
    image: uslugi,
    type: 'bottom',
    tag: 'significant',
    rating: 2,
  },
  {
    id: 5,
    title: 'Единая карта петербуржца',
    subtitle: 'Образовательынй онлайн портал',
    mark: 'new',
    image: map,
    type: 'top',
    tag: 'significant',
    rating: 2.2,
  },
  {
    id: 6,
    title: 'Открытый город',
    subtitle: 'Информация о новом социальном проекте',
    mark: 'favorite',
    image: openCity,
    type: 'top',
    rating: 4.9,
  },
  {
    id: 7,
    title: 'Здоровье петербуржца',
    subtitle: 'Краткое описание Поддержка и развитие регионов  и развитие регионов',

    image: health,
    type: 'top',
    rating: 3.5,
  },
  {
    id: 8,
    title: 'Твой бюждет',
    subtitle: 'Краткое описание Поддержка и развитие регионов  и развитие регионов',
    mark: 'popular',
    image: openCity,
    type: 'bottom',
    rating: 4.3,
  },
  {
    id: 9,
    title: 'Наш Санкт-Петербург',
    subtitle: 'Краткое описание Поддержка и развитие регионов  и развитие регионов',
    mark: 'popular',
    image: health,
    type: 'bottom',
    rating: 3.2,
  },
  {
    id: 10,
    title: 'Мои документы',
    subtitle: 'Государственные и муниципальные услуги',
    mark: 'popular',
    image: health,
    type: 'bottom',
    rating: 2,
  },
  {
    id: 11,
    title: 'Единая карта петербуржца',
    subtitle: 'Образовательынй онлайн портал',
    mark: 'new',
    image: map,
    type: 'top',
    rating: 5,
  },
  {
    id: 12,
    title: 'Открытый город',
    subtitle: 'Информация о новом социальном проекте',
    mark: 'favorite',
    image: health,
    type: 'bottom',
    rating: 4,
  },
];
