import uslugi from '../../../../public/assets/article/uslugi.svg';
import vk from '../../../../public/assets/icons/fa-solid_vk.svg';
import yandex from '../../../../public/assets/icons/fa-solid_yandex.svg';
import web from '../../../../public/assets/icons/fa-solid_web.svg';
import googlePlay from '../../../../public/assets/icons/fa-solid_google-play.svg';
import apple from '../../../../public/assets/icons/fa-solid_apple.svg';
import bot from '../../../../public/assets/icons/fa-solid_robot.svg';

export const CATALOG_CARDS_ARRAY = [
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 1,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 2,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 3,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 4,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 5,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 6,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 7,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 8,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 9,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 10,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 11,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 12,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 13,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 14,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 15,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 16,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 17,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 18,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 20,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 23,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 25,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 27,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 265,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 3535,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 325325,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 345325,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 31532,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 2355235,
  },
];
export const FILTER_OPTIONS = [
  { value: 'Все', label: 'Все' },
  { value: 'По алфавиту', label: 'По алфавиту' },
  { value: 'По новизне', label: 'По новизне' },
];

export const INTERESTED_CARDS = [
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about:
      'Портала электронных сервисов здравоохранения принадлежит Комитету по здравоохранению и Администрации города Санкт-Петербурга',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 1,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 2,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 3,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 5,
    developer: 'MailGroup',
    socialNetworks: [{ title: 'Вконтакте', href: 'vk.com' }],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 5,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 3.5,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 5,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 6,
  },
  {
    title: 'Санкт-Петербург госуслуги',
    icon: uslugi,
    link: { href: 'spp.ru', text: 'spp.ru' },
    about: 'VK Combo — это скидки на такси, заказ еды и покупки, а ещё бесплатная музыка и онлайн-кинотеатры',
    rating: 4,
    developer: 'MailGroup',
    socialNetworks: [
      { title: 'Вконтакте', href: 'vk.com' },
      { title: 'Инстаграм', href: 'instagram.com' },
    ],
    updated: '15 мая 2021',
    reviewsCount: 14,
    tabletLinks: [
      { icon: web, title: 'website.spb.ru', href: 'http://website.spb.ru' },
      { icon: vk, title: 'mini app', href: 'http://vk.com' },
      { icon: yandex, title: 'Yandex', href: 'http://yandex.ru' },
      { icon: googlePlay, title: 'Google Play', href: 'http://google.com' },
      { icon: apple, title: 'App store', href: 'http://App-store.com' },
      { icon: bot, title: 'Чат-бот', href: 'http://chat-bot.com' },
    ],
    id: 7,
  },
];
